version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-group
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456kc
      MYSQL_DATABASE: EV_db
      MYSQL_USER: groupuser
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
